create table person (
    id BIGSERIAL NOT NULL PRIMARY KEY,
	first_name VARCHAR(120) NOT NULL,
	last_name VARCHAR(150) NOT NULL,
	email VARCHAR(90),
	gender VARCHAR(12) NOT NULL,
	date_of_birth DATE NOT NULL,
	country VARCHAR(50) NOT NULL
);
insert into person (first_name, last_name, email, gender, date_of_birth, country) values ('Emelda', 'Duligal', 'eduligal0@tumblr.com', 'Female', '02/07/2024', 'China');
insert into person (first_name, last_name, email, gender, date_of_birth, country) values ('Fifine', 'Skeleton', 'fskeleton1@earthlink.net', 'Agender', '10/04/2024', 'Chile');
insert into person (first_name, last_name, email, gender, date_of_birth, country) values ('Mirabel', 'Yaldren', 'myaldren2@arstechnica.com', 'Female', '18/01/2025', 'Poland');
insert into person (first_name, last_name, email, gender, date_of_birth, country) values ('Carny', 'Albrooke', 'calbrooke3@bluehost.com', 'Male', '26/09/2024', 'El Salvador');
insert into person (first_name, last_name, email, gender, date_of_birth, country) values ('Booth', 'Toffalo', 'btoffalo4@furl.net', 'Male', '09/03/2025', 'Serbia');
insert into person (first_name, last_name, email, gender, date_of_birth, country) values ('Erminia', 'Pudsall', 'epudsall5@ustream.tv', 'Female', '07/10/2024', 'Vietnam');
insert into person (first_name, last_name, email, gender, date_of_birth, country) values ('Clem', 'Luty', 'cluty6@microsoft.com', 'Male', '02/04/2025', 'Albania');
insert into person (first_name, last_name, email, gender, date_of_birth, country) values ('Kittie', 'MacCaughan', 'kmaccaughan7@github.io', 'Female', '14/04/2024', 'China');
insert into person (first_name, last_name, email, gender, date_of_birth, country) values ('Abrahan', 'Emmett', 'aemmett8@parallels.com', 'Male', '19/08/2024', 'Poland');
insert into person (first_name, last_name, email, gender, date_of_birth, country) values ('Colette', 'Hollindale', 'chollindale9@youtube.com', 'Female', '24/11/2024', 'Brazil');
insert into person (first_name, last_name, email, gender, date_of_birth, country) values ('Merissa', 'Durgan', 'mdurgana@omniture.com', 'Female', '27/02/2025', 'Norway');
insert into person (first_name, last_name, email, gender, date_of_birth, country) values ('Demetris', 'Cowper', 'dcowperb@yahoo.com', 'Female', '28/01/2025', 'China');
insert into person (first_name, last_name, email, gender, date_of_birth, country) values ('Whitney', 'Abotson', 'wabotsonc@google.it', 'Male', '21/02/2025', 'Portugal');
insert into person (first_name, last_name, email, gender, date_of_birth, country) values ('Jillene', 'Jickles', 'jjicklesd@meetup.com', 'Female', '29/06/2024', 'Indonesia');
insert into person (first_name, last_name, email, gender, date_of_birth, country) values ('Donny', 'Camel', 'dcamele@prlog.org', 'Male', '18/07/2024', 'Mongolia');
insert into person (first_name, last_name, email, gender, date_of_birth, country) values ('Blane', 'Bleyman', 'bbleymanf@cam.ac.uk', 'Male', '20/02/2025', 'Peru');
insert into person (first_name, last_name, email, gender, date_of_birth, country) values ('Curran', 'Spilsted', 'cspilstedg@linkedin.com', 'Male', '19/02/2025', 'Honduras');
insert into person (first_name, last_name, email, gender, date_of_birth, country) values ('Adair', 'Ilive', 'ailiveh@cnn.com', 'Male', '21/08/2024', 'Ukraine');
insert into person (first_name, last_name, email, gender, date_of_birth, country) values ('Hartwell', 'Kun', 'hkuni@fastcompany.com', 'Male', '11/08/2024', 'China');
insert into person (first_name, last_name, email, gender, date_of_birth, country) values ('Arty', 'Darlasson', 'adarlassonj@indiatimes.com', 'Male', '11/12/2024', 'Japan');
insert into person (first_name, last_name, email, gender, date_of_birth, country) values ('Katleen', 'Learned', 'klearnedk@ed.gov', 'Female', '04/07/2024', 'Indonesia');
insert into person (first_name, last_name, email, gender, date_of_birth, country) values ('Donielle', 'Faussett', 'dfaussettl@walmart.com', 'Female', '28/12/2024', 'Greece');
insert into person (first_name, last_name, email, gender, date_of_birth, country) values ('Farly', 'Scrowson', 'fscrowsonm@sourceforge.net', 'Male', '15/12/2024', 'Russia');
insert into person (first_name, last_name, email, gender, date_of_birth, country) values ('Sax', 'Huller', 'shullern@state.gov', 'Male', '15/08/2024', 'Poland');
insert into person (first_name, last_name, email, gender, date_of_birth, country) values ('Carlyn', 'Hubbis', 'chubbiso@si.edu', 'Female', '05/12/2024', 'Japan');
insert into person (first_name, last_name, email, gender, date_of_birth, country) values ('Ardelis', 'Devil', 'adevilp@furl.net', 'Agender', '05/02/2025', 'Ukraine');
insert into person (first_name, last_name, email, gender, date_of_birth, country) values ('Willa', 'Goodhay', 'wgoodhayq@uol.com.br', 'Female', '06/09/2024', 'Japan');
insert into person (first_name, last_name, email, gender, date_of_birth, country) values ('Willard', 'Strother', 'wstrotherr@google.de', 'Male', '15/08/2024', 'Costa Rica');
insert into person (first_name, last_name, email, gender, date_of_birth, country) values ('Ferdinande', 'Alcido', 'falcidos@netvibes.com', 'Female', '29/11/2024', 'Nigeria');
insert into person (first_name, last_name, email, gender, date_of_birth, country) values ('Nada', 'Shimoni', 'nshimonit@gnu.org', 'Female', '31/07/2024', 'Pakistan');
insert into person (first_name, last_name, email, gender, date_of_birth, country) values ('Munroe', 'Headings', 'mheadingsu@instagram.com', 'Male', '29/10/2024', 'Iran');
insert into person (first_name, last_name, email, gender, date_of_birth, country) values ('Germain', 'Maudson', 'gmaudsonv@csmonitor.com', 'Male', '22/11/2024', 'Indonesia');
insert into person (first_name, last_name, email, gender, date_of_birth, country) values ('Rebbecca', 'Dubber', 'rdubberw@usatoday.com', 'Female', '13/06/2024', 'Greece');
insert into person (first_name, last_name, email, gender, date_of_birth, country) values ('Aldric', 'Saffran', 'asaffranx@nationalgeographic.com', 'Male', '23/10/2024', 'China');
insert into person (first_name, last_name, email, gender, date_of_birth, country) values ('Jessie', 'Alelsandrovich', 'jalelsandrovichy@vkontakte.ru', 'Female', '20/02/2025', 'Colombia');
insert into person (first_name, last_name, email, gender, date_of_birth, country) values ('Elita', 'Klamman', 'eklammanz@samsung.com', 'Female', '29/08/2024', 'Indonesia');
insert into person (first_name, last_name, email, gender, date_of_birth, country) values ('Valera', 'Tolliday', 'vtolliday10@barnesandnoble.com', 'Female', '26/01/2025', 'China');
insert into person (first_name, last_name, email, gender, date_of_birth, country) values ('Perla', 'Leftridge', 'pleftridge11@craigslist.org', 'Female', '16/06/2024', 'Dominican Republic');
insert into person (first_name, last_name, email, gender, date_of_birth, country) values ('Clifford', 'Leverett', 'cleverett12@google.co.jp', 'Male', '06/08/2024', 'Luxembourg');
insert into person (first_name, last_name, email, gender, date_of_birth, country) values ('Linzy', 'Galbreth', 'lgalbreth13@meetup.com', 'Female', '15/04/2024', 'Costa Rica');
insert into person (first_name, last_name, email, gender, date_of_birth, country) values ('Artur', 'Schrir', 'aschrir14@kickstarter.com', 'Male', '30/08/2024', 'Palestinian Territory');
insert into person (first_name, last_name, email, gender, date_of_birth, country) values ('Othilia', 'Ivantsov', 'oivantsov15@foxnews.com', 'Female', '11/08/2024', 'Peru');
insert into person (first_name, last_name, email, gender, date_of_birth, country) values ('Burg', 'Motion', 'bmotion16@bloomberg.com', 'Genderfluid', '01/05/2024', 'Tunisia');
insert into person (first_name, last_name, email, gender, date_of_birth, country) values ('Vittoria', 'Godbehere', 'vgodbehere17@microsoft.com', 'Female', '25/06/2024', 'Portugal');
insert into person (first_name, last_name, email, gender, date_of_birth, country) values ('Solly', 'Whyler', 'swhyler18@flavors.me', 'Male', '07/01/2025', 'Japan');
insert into person (first_name, last_name, email, gender, date_of_birth, country) values ('Owen', 'Cardenas', 'ocardenas19@ycombinator.com', 'Male', '03/08/2024', 'Tunisia');
insert into person (first_name, last_name, email, gender, date_of_birth, country) values ('Peirce', 'Aujean', 'paujean1a@meetup.com', 'Male', '17/06/2024', 'Sweden');
insert into person (first_name, last_name, email, gender, date_of_birth, country) values ('Benoit', 'Brann', 'bbrann1b@msu.edu', 'Male', '15/02/2025', 'Indonesia');
insert into person (first_name, last_name, email, gender, date_of_birth, country) values ('Scot', 'Wadman', 'swadman1c@1und1.de', 'Male', '10/02/2025', 'Yemen');
insert into person (first_name, last_name, email, gender, date_of_birth, country) values ('Dougie', 'Meneo', 'dmeneo1d@unblog.fr', 'Male', '19/02/2025', 'Philippines');
insert into person (first_name, last_name, email, gender, date_of_birth, country) values ('Marietta', 'Schoffel', 'mschoffel1e@xinhuanet.com', 'Male', '10/01/2025', 'China');
insert into person (first_name, last_name, email, gender, date_of_birth, country) values ('Ellswerth', 'Diemer', 'ediemer1f@furl.net', 'Male', '07/11/2024', 'China');
insert into person (first_name, last_name, email, gender, date_of_birth, country) values ('Mal', 'O''Hederscoll', 'mohederscoll1g@archive.org', 'Male', '22/12/2024', 'China');
insert into person (first_name, last_name, email, gender, date_of_birth, country) values ('Pia', 'McEvoy', 'pmcevoy1h@icio.us', 'Female', '28/12/2024', 'Colombia');
insert into person (first_name, last_name, email, gender, date_of_birth, country) values ('Kathi', 'Barhems', 'kbarhems1i@skype.com', 'Female', '11/06/2024', 'France');
insert into person (first_name, last_name, email, gender, date_of_birth, country) values ('Erl', 'Leward', 'eleward1j@pagesperso-orange.fr', 'Polygender', '10/06/2024', 'France');
insert into person (first_name, last_name, email, gender, date_of_birth, country) values ('Ellwood', 'Arne', 'earne1k@alexa.com', 'Male', '15/05/2024', 'Argentina');
insert into person (first_name, last_name, email, gender, date_of_birth, country) values ('Teddie', 'Lanfare', 'tlanfare1l@uiuc.edu', 'Male', '05/12/2024', 'Morocco');
insert into person (first_name, last_name, email, gender, date_of_birth, country) values ('Nita', 'Town', 'ntown1m@bbc.co.uk', 'Female', '22/01/2025', 'Japan');
insert into person (first_name, last_name, email, gender, date_of_birth, country) values ('Chico', 'Bernholt', 'cbernholt1n@microsoft.com', 'Male', '30/08/2024', 'Portugal');
insert into person (first_name, last_name, email, gender, date_of_birth, country) values ('Booth', 'Tremelling', 'btremelling1o@newsvine.com', 'Male', '09/11/2024', 'China');
insert into person (first_name, last_name, email, gender, date_of_birth, country) values ('Vail', 'Maudlin', 'vmaudlin1p@eventbrite.com', 'Male', '13/08/2024', 'Indonesia');
insert into person (first_name, last_name, email, gender, date_of_birth, country) values ('Son', 'Jorgensen', 'sjorgensen1q@scribd.com', 'Male', '23/11/2024', 'Russia');
insert into person (first_name, last_name, email, gender, date_of_birth, country) values ('Stearne', 'Tenwick', 'stenwick1r@huffingtonpost.com', 'Male', '20/01/2025', 'Venezuela');
insert into person (first_name, last_name, email, gender, date_of_birth, country) values ('Paquito', 'Scown', 'pscown1s@mac.com', 'Male', '12/09/2024', 'China');
insert into person (first_name, last_name, email, gender, date_of_birth, country) values ('Christa', 'Kettlesing', 'ckettlesing1t@census.gov', 'Genderqueer', '17/04/2024', 'Nigeria');
insert into person (first_name, last_name, email, gender, date_of_birth, country) values ('Brnaby', 'Bleiman', 'bbleiman1u@tamu.edu', 'Male', '01/12/2024', 'Canada');
insert into person (first_name, last_name, email, gender, date_of_birth, country) values ('Timmi', 'Nabarro', 'tnabarro1v@goodreads.com', 'Female', '30/01/2025', 'Slovenia');
insert into person (first_name, last_name, email, gender, date_of_birth, country) values ('Ward', 'Peplaw', 'wpeplaw1w@jalbum.net', 'Male', '20/01/2025', 'Czech Republic');
insert into person (first_name, last_name, email, gender, date_of_birth, country) values ('Delora', 'Champion', 'dchampion1x@craigslist.org', 'Female', '30/06/2024', 'China');
insert into person (first_name, last_name, email, gender, date_of_birth, country) values ('Maxim', 'Peakman', 'mpeakman1y@addthis.com', 'Male', '14/04/2024', 'Indonesia');
insert into person (first_name, last_name, email, gender, date_of_birth, country) values ('Dione', 'Srawley', 'dsrawley1z@chron.com', 'Female', '14/04/2024', 'China');
insert into person (first_name, last_name, email, gender, date_of_birth, country) values ('Melinde', 'Sambiedge', 'msambiedge20@nyu.edu', 'Female', '25/06/2024', 'Russia');
insert into person (first_name, last_name, email, gender, date_of_birth, country) values ('Bette-ann', 'Rowland', 'browland21@apple.com', 'Female', '02/04/2025', 'Philippines');
insert into person (first_name, last_name, email, gender, date_of_birth, country) values ('Tedie', 'McKinn', 'tmckinn22@army.mil', 'Male', '27/11/2024', 'Russia');
insert into person (first_name, last_name, email, gender, date_of_birth, country) values ('Lissy', 'Nenci', 'lnenci23@google.de', 'Female', '15/08/2024', 'Czech Republic');
insert into person (first_name, last_name, email, gender, date_of_birth, country) values ('Monah', 'Panketh', 'mpanketh24@unblog.fr', 'Female', '08/07/2024', 'Japan');
insert into person (first_name, last_name, email, gender, date_of_birth, country) values ('Conn', 'Hourston', 'chourston25@seattletimes.com', 'Male', '26/10/2024', 'Poland');
insert into person (first_name, last_name, email, gender, date_of_birth, country) values ('Janelle', 'Druitt', 'jdruitt26@columbia.edu', 'Female', '31/07/2024', 'China');
insert into person (first_name, last_name, email, gender, date_of_birth, country) values ('Roxanna', 'Skechley', 'rskechley27@npr.org', 'Female', '04/07/2024', 'United Kingdom');
insert into person (first_name, last_name, email, gender, date_of_birth, country) values ('Derward', 'Farny', 'dfarny28@tmall.com', 'Male', '12/11/2024', 'China');
insert into person (first_name, last_name, email, gender, date_of_birth, country) values ('Kiah', 'Dark', 'kdark29@noaa.gov', 'Female', '02/09/2024', 'Iran');
insert into person (first_name, last_name, email, gender, date_of_birth, country) values ('Naomi', 'Gilbey', 'ngilbey2a@cargocollective.com', 'Female', '06/10/2024', 'Netherlands');
insert into person (first_name, last_name, email, gender, date_of_birth, country) values ('Adrian', 'Vain', 'avain2b@newsvine.com', 'Male', '13/03/2025', 'Vietnam');
insert into person (first_name, last_name, email, gender, date_of_birth, country) values ('Edithe', 'Gentile', 'egentile2c@sakura.ne.jp', 'Female', '03/12/2024', 'American Samoa');
insert into person (first_name, last_name, email, gender, date_of_birth, country) values ('Nikolaus', 'Hosten', 'nhosten2d@unesco.org', 'Genderqueer', '21/06/2024', 'China');
insert into person (first_name, last_name, email, gender, date_of_birth, country) values ('Desdemona', 'Bollen', 'dbollen2e@hatena.ne.jp', 'Female', '13/06/2024', 'China');
insert into person (first_name, last_name, email, gender, date_of_birth, country) values ('Kerr', 'Janssen', 'kjanssen2f@skype.com', 'Male', '06/10/2024', 'Thailand');
insert into person (first_name, last_name, email, gender, date_of_birth, country) values ('Marcelia', 'Galbreth', 'mgalbreth2g@mozilla.org', 'Female', '11/02/2025', 'Iran');
insert into person (first_name, last_name, email, gender, date_of_birth, country) values ('Aprilette', 'Scantlebury', 'ascantlebury2h@mail.ru', 'Female', '11/09/2024', 'China');
insert into person (first_name, last_name, email, gender, date_of_birth, country) values ('Joel', 'Vassbender', 'jvassbender2i@twitter.com', 'Male', '19/01/2025', 'Poland');
insert into person (first_name, last_name, email, gender, date_of_birth, country) values ('Cassius', 'Ilyinski', 'cilyinski2j@cnn.com', 'Male', '14/10/2024', 'Bulgaria');
insert into person (first_name, last_name, email, gender, date_of_birth, country) values ('Jaye', 'Hainge', 'jhainge2k@harvard.edu', 'Male', '19/08/2024', 'Lithuania');
insert into person (first_name, last_name, email, gender, date_of_birth, country) values ('Dixie', 'Penketh', 'dpenketh2l@elegantthemes.com', 'Female', '11/02/2025', 'Brazil');
insert into person (first_name, last_name, email, gender, date_of_birth, country) values ('Cristina', 'Christy', 'cchristy2m@blogtalkradio.com', 'Female', '05/09/2024', 'North Korea');
insert into person (first_name, last_name, email, gender, date_of_birth, country) values ('Saraann', 'Capaldi', 'scapaldi2n@cargocollective.com', 'Female', '28/07/2024', 'Dominican Republic');
insert into person (first_name, last_name, email, gender, date_of_birth, country) values ('Gerrard', 'Cicconetti', 'gcicconetti2o@paginegialle.it', 'Male', '31/03/2025', 'Brazil');
insert into person (first_name, last_name, email, gender, date_of_birth, country) values ('Arty', 'Binford', 'abinford2p@twitter.com', 'Male', '02/10/2024', 'Mongolia');
insert into person (first_name, last_name, email, gender, date_of_birth, country) values ('Carin', 'Izen', 'cizen2q@hubpages.com', 'Female', '01/12/2024', 'United States');
insert into person (first_name, last_name, email, gender, date_of_birth, country) values ('Tiffani', 'Inderwick', 'tinderwick2r@sohu.com', 'Female', '16/08/2024', 'Sweden');